### ISSUE TITLE
Arch Linux link broken

### ISSUE THREAD

**Issue by tbm** [ledger/ledger-website#32]
The website links to https://aur.archlinux.org/packages/ledger/ but this doesn't exist anymore.

There is https://aur.archlinux.org/packages/ledger-git/ but that's the development version.

Is there no stable package for ledger for Arch anymore?  @wzyboy, do you know?

**Comment by wzyboy** [comment]
It has been moved from AUR to "community" repo: https://www.archlinux.org/packages/community/x86_64/ledger/
