### ISSUE TITLE
travis CI is failing, blocking updates

### ISSUE THREAD

**Issue by simonmichael** [ledger/ledger-website#36]
[Moved here from 9/28 email]

Hi @peterkeen,

I fixed https://github.com/ledger/ledger-website/commit/5daf18ca1a1e3b6e360f4bddb6c4000b49eca15a , but the travis build failed: https://travis-ci.org/ledger/ledger-website/builds/590834140 and it hasn't deployed. Maybe this is relevant:

Output written on ledger.pdf (53 pages, 276000 bytes).
Transcript written on ledger.log.
/usr/bin/texi2dvi: pdfetex exited with bad status, quitting.
/usr/bin/texi2dvi: Removing /home/travis/build/ledger/[secure]/ledger.t2d
 [118]Makefile:41: recipe for target 'ledger.pdf' failed
make: *** [ledger.pdf] Error 1

I got your name from the about this website page. Could you fix and deploy ? Thanks,

[And Travis is sending me a daily reminder about it.]

**Comment by peterkeen** [comment]
Fixed! Step one was to pin Travis on `trusty` (see #35). That worked, so then I tried `bionic` (ubuntu 18.04) which also worked. Something about `xenial`'s TeX just didn't agree with our docs.
