### ISSUE TITLE
Update PDF version of manual to latest release

### ISSUE THREAD

**Issue by afh** [ledger/ledger-website#45]
The PDF version of the manual (available from https://www.ledger-cli.org/3.0/doc/ledger3.pdf) is for Ledger version 3.2.1 and should be updated to 3.3.0.

**Comment by afh** [comment]
Thanks for taking care of this @tbm 👍

**Comment by tbm** [comment]
Note that the web site is not getting updated because Travis is not run. I'll open a ticket
